### ISSUE TITLE
MjbotsControlLoop should have init member function

### ISSUE THREAD

**Issue by jdcaporale** [KodlabPenn/kodlab_mjbots_sdk#23]
Currently any one off setup needs to be custom made into a constructor or put behind some sort of initial_call flag in CalcTorques(). MjbotsControlLoop should probably have a non-pure virtual function Init(), Begin(),  or equivalent.

**Comment by ethanmusser** [comment]
There are some issues with putting virtual functions inside constructors.  However, this virtual `Init` function could be called at the beginning of the `Run` function, which is where we currently do most of our intitialization.
