### ISSUE TITLE
Base classes need virtual destructors

### ISSUE THREAD

**Issue by ethanmusser** [KodlabPenn/kodlab_mjbots_sdk#49]
Discussions in #39 pointed out that some of our inherited classes may not have a virtual destructor.  As discussed [here (in the _Virtual Destructors_ section)](https://en.cppreference.com/w/cpp/language/destructor), virtual destructors are necessary in base classes to permit appropriate destruction of derived classes through pointers to their base.  

TODO:

- [x] Add virtual destructors to all inherited classes which do not have them.

**Comment by ShaneRozenLevy** [comment]
I think the biggest improvement here is that it will probably stop the code from seg faulting on exit.

**Comment by ethanmusser** [comment]
Actually I think we unintentionally fixed that at some point along the way, the code doesn't seg fault on exit anymore.  But a good preventative measure nonetheless.

**Comment by jdcaporale** [comment]
#89 Did this.
